.\" generated with Ronn-NG/v0.8.2
.\" http://github.com/apjanke/ronn-ng/tree/0.8.2
.TH "GIT\-PR" "1" "May 2019" "" ""
.SH "NAME"
\fBgit\-pr\fR \-
.SH "SYNOPSIS"
git\-pr [branch]
.P
\fBbranch\fR \- if passed, it will create a new branch "kek" and will open a github link with suggest to create a PR\. Otherwise it will open existing PR for current branch (no sense to call it from master)
.SH "DESCRIPTION"
A helper script for git and github to create new / open existing PR for your branches
.SH "COPYRIGHT"
(c) 2019 Jerry Green
.P
MIT license
